import React from 'react'
import Item from './item.component'

const Accordion = () => {
  return (
    <div className='questions-accordion mx-auto md:w-[800px] lg:w-2/3'>
      <Item title="What is Satellitor, and how does it work to drive traffic to my website?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur deserunt neque provident, doloribus mollitia voluptatibus deleniti voluptas cumque animi soluta quis. Ex laudantium a exercitationem enim, ut voluptatum accusamus aperiam natus? Nihil quis ullam, laboriosam error eveniet minima. Qui accusantium dolore tenetur quod beatae vel explicabo itaque odit cum consequuntur." />
      <Item title="Can I trust AI with my SEO needs, and how does it compare to human input?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur deserunt neque provident, doloribus mollitia voluptatibus deleniti voluptas cumque animi soluta quis. Ex laudantium a exercitationem enim, ut voluptatum accusamus aperiam natus? Nihil quis ullam, laboriosam error eveniet minima. Qui accusantium dolore tenetur quod beatae vel explicabo itaque odit cum consequuntur." />
      <Item title="Does Satellitor work with non-English content?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur deserunt neque provident, doloribus mollitia voluptatibus deleniti voluptas cumque animi soluta quis. Ex laudantium a exercitationem enim, ut voluptatum accusamus aperiam natus? Nihil quis ullam, laboriosam error eveniet minima. Qui accusantium dolore tenetur quod beatae vel explicabo itaque odit cum consequuntur." />
      <Item title="Can Satellitor help me with topics and keywords?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur deserunt neque provident, doloribus mollitia voluptatibus deleniti voluptas cumque animi soluta quis. Ex laudantium a exercitationem enim, ut voluptatum accusamus aperiam natus? Nihil quis ullam, laboriosam error eveniet minima. Qui accusantium dolore tenetur quod beatae vel explicabo itaque odit cum consequuntur." />
      <Item title="What does 'SEO optimized' mean?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur deserunt neque provident, doloribus mollitia voluptatibus deleniti voluptas cumque animi soluta quis. Ex laudantium a exercitationem enim, ut voluptatum accusamus aperiam natus? Nihil quis ullam, laboriosam error eveniet minima. Qui accusantium dolore tenetur quod beatae vel explicabo itaque odit cum consequuntur." />
      <Item title="Is payment secure?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur deserunt neque provident, doloribus mollitia voluptatibus deleniti voluptas cumque animi soluta quis. Ex laudantium a exercitationem enim, ut voluptatum accusamus aperiam natus? Nihil quis ullam, laboriosam error eveniet minima. Qui accusantium dolore tenetur quod beatae vel explicabo itaque odit cum consequuntur." />
      <Item title="Is it possible to get a refund?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur deserunt neque provident, doloribus mollitia voluptatibus deleniti voluptas cumque animi soluta quis. Ex laudantium a exercitationem enim, ut voluptatum accusamus aperiam natus? Nihil quis ullam, laboriosam error eveniet minima. Qui accusantium dolore tenetur quod beatae vel explicabo itaque odit cum consequuntur." />
      <Item title="Can I cancel my subscription at any time?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur deserunt neque provident, doloribus mollitia voluptatibus deleniti voluptas cumque animi soluta quis. Ex laudantium a exercitationem enim, ut voluptatum accusamus aperiam natus? Nihil quis ullam, laboriosam error eveniet minima. Qui accusantium dolore tenetur quod beatae vel explicabo itaque odit cum consequuntur." />
      <Item title="What happens to my content if I stop my subscription?" content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur deserunt neque provident, doloribus mollitia voluptatibus deleniti voluptas cumque animi soluta quis. Ex laudantium a exercitationem enim, ut voluptatum accusamus aperiam natus? Nihil quis ullam, laboriosam error eveniet minima. Qui accusantium dolore tenetur quod beatae vel explicabo itaque odit cum consequuntur." />
    </div>
  )
}

export default Accordion
